# Generated by Django 5.0.2 on 2025-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
    ]
